name: CI

on:
  pull_request:
    branches: ['main']
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.gitignore'
  workflow_dispatch:

jobs:
  on-push-checks:
    name: "On-push checks"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v5"

      - name: "Set up PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: '8.3'
          coverage: xdebug

      - name: "Install dependencies"
        env:
          COMPOSER_AUTH: '${{ secrets.COMPOSER_AUTH }}'
        run: 'composer update'

      - name: "Run PHPCS checks"
        run: "./bin/php-cs ./src ./tests"

      - name: "Run PHPStan static analysis"
        run: "./bin/phpstan analyse --no-progress"

      - name: "Run PHPUnit tests"
        env:
          XDEBUG_MODE: "coverage"
        run: "php -d memory_limit=-1 ./bin/phpunit"
