on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  deploy:
    name: 'Deploy Cloud Function'
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'

      - name: 'Authenticate with GCP'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/${{ vars.GCP_PROJECT_ID }}/locations/global/workloadIdentityPools/${{ vars.GCP_WIF_POOL }}/providers/${{ vars.GCP_WIF_PROVIDER }}'
          service_account: '${{ vars.GCP_SERVICE_ACCOUNT }}'

      - name: 'Create or update Cloud Function'
        id: 'deploy'
        uses: 'google-github-actions/deploy-cloud-functions@v1'
        with:
          build_environment_variables: 'COMPOSER_AUTH={"github-oauth":{"github.com":"${{ secrets.COMPOSER_GITHUB_TOKEN }}"}}'
          deploy_timeout: 600
          entry_point: 'run'
          env_vars: 'USE_CACHE_TTL=300,USE_CACHE_BUT_REQUEST_TTL=600,USE_CACHE_IF_ERROR_TTL=3600'
          https_trigger_security_level: 'secure_always'
          max_instances: 1
          memory_mb: '128'
          min_instances: 0
          name: '${{ vars.GCP_CLOUD_FUNCTION_ENDPOINT }}'
          region: 'europe-west2'
          runtime: 'php82'
          secret_environment_variables: 'SMARTTHINGS_API_TOKEN=projects/${{ vars.GCP_PROJECT_ID }}/secrets/SMARTTHINGS_API_TOKEN,REQUIRED_HEADER_KEY=projects/${{ vars.GCP_PROJECT_ID }}/secrets/SMARTTHINGS_REQUIRED_HEADER_KEY,REQUIRED_HEADER_VALUE=projects/${{ vars.GCP_PROJECT_ID }}/secrets/SMARTTHINGS_REQUIRED_HEADER_VALUE,REQUIRED_ORIGIN=projects/${{ vars.GCP_PROJECT_ID }}/secrets/SMARTTHINGS_REQUIRED_ORIGIN'
          timeout: 60

      - name: 'Test Cloud Function'
        run: 'curl "${{ steps.deploy.outputs.url }}"'
